name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Checksum
        uses: ToxicAven/generate-checksum-file@v2
        with:
          filePath: .github/repo/plugin.video.aiostreams/plugin.video.aiostreams-3.5.19.zip
          saveFile: .github/repo/plugin.video.aiostreams/plugin.video.aiostreams-3.5.19.zip.md5
          algorithm: MD5
